name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'alpine'
          #- 'debian'
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: docker image Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: './Dockerfile'
        tags: 'davyinsa/pareviewsh' 
